POST http://api-blog-laravel.com/api/register
Content-type: application/x-www-form-urlencoded

json: """{
	"name": "Luis",
	"surname": "Villarreal",
	"email": "luis@me.com",
	"password": "luis12345"
}"""