
PUT http://api-blog-laravel.com/api/user/update
Content-type: application/x-www-form-urlencoded
Authorization: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEwLCJlbWFpbCI6Imx1aXNAbWUuY29tIiwibmFtZSI6Ikx1aXMiLCJzdXJuYW1lIjoiVmlsbGFycmVhbCIsImlhdCI6MTY3NDE5MDA3NiwiZXhwIjoxNjc0Nzk0ODc2fQ.eDyopgebeNGo2noas15KkjQqT4CcAfxSUQMBSbtf_Wo"

json: """{
	"name": "Luis",
	"surname": "Villarreal Cig",
	"email": "luis@me.com",
	"password": "luis12345"
}"""
